// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xinpddlavyqkgwnkncst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpbnBkZGxhdnlxa2d3bmtuY3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NTAwOTMsImV4cCI6MjA3NDMyNjA5M30.xLe606XO5M0Dq3hIVPwNYaVAuBSC0VaLrjjawIdeCrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});